version: '3.3'

services:
  influxdb:
    image: influxdb:1.8.1
    container_name: mon_influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.1.3
    container_name: mon_grafana
    restart: always
    depends_on:
      - influxdb
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards

  loki:
    image: grafana/loki:1.6.0
    container_name: mon_loki
    restart: always
    user: "1000"
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
